import { WeekData } from "./base";

const testData2: Array<WeekData> = [
  {
    // bin: 0,
    bins: [
      { value: -1 },
      { value: -1 },
      { value: -1 },
      { value: -1 },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 1,
    bins: [
      { value: 0, workflowCount: 10 },
      { value: 14, workflowCount: 10 },
      { value: 27, workflowCount: 10 },
      { value: 40, workflowCount: 10 },
      { value: 50, workflowCount: 10 },
      { value: 60, workflowCount: 10 },
      { value: 70, workflowCount: 10 },
    ],
  },
  {
    // bin: 2,
    bins: [
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 4,
    bins: [
      { value: 60 },
      { value: 70 },
      { value: 80 },
      { value: 90 },
      { value: 99 },
      { value: 100 },
      { value: NaN },
    ],
  },
  {
    // bin: 5,
    bins: [
      { value: 20 },
      { value: 20 },
      { value: 20 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 40 },
    ],
  },
  {
    // bin: 5,
    bins: [
      { value: 20 },
      { value: 20 },
      { value: 20 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 6,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 70 },
      { value: 80 },
      { value: 90 },
      { value: 100 },
    ],
  },
  {
    // bin: 7,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 8,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 9,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 10,
    bins: [
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 11,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 12,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 13,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 100 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 14,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 15,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 16,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: 10 },
    ],
  },
  {
    // bin: 17,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: NaN },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 18,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 19,
    bins: [
      { value: 10 },
      { value: NaN },
      { value: NaN },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 20,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 21,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 0,
    bins: [
      { value: 10 },
      { value: 10 },
      { value: NaN },
      { value: 10 },
      { value: 10 },
      { value: 10 },
      { value: 1 },
    ],
  },
  {
    // bin: 1,
    bins: [
      { value: 0 },
      { value: 14 },
      { value: 27 },
      { value: 40 },
      { value: 50 },
      { value: 60 },
      { value: 70 },
    ],
  },
  {
    // bin: 2,
    bins: [
      { value: 80 },
      { value: 90 },
      { value: 100 },
      { value: 0 },
      { value: 15 },
      { value: 25 },
      { value: 40 },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: 10 },
      { value: 20 },
      { value: 30 },
      { value: 40 },
      { value: 50 },
      { value: 50 },
      { value: 50 },
    ],
  },
  {
    // bin: 4,
    bins: [
      { value: 60 },
      { value: 70 },
      { value: 80 },
      { value: 90 },
      { value: 99 },
      { value: 100 },
      { value: NaN },
    ],
  },
  {
    // bin: 5,
    bins: [
      { value: 20 },
      { value: 20 },
      { value: 20 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 40 },
    ],
  },
  {
    // bin: 5,
    bins: [
      { value: 20 },
      { value: 20 },
      { value: 20 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 6,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 70 },
      { value: 80 },
      { value: 90 },
      { value: 100 },
    ],
  },
  {
    // bin: 7,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 8,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 9,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 10,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 11,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 12,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 13,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 100 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 14,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 15,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 16,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 17,
    bins: [
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
      { value: NaN },
    ],
  },
  {
    // bin: 18,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 19,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 20,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 21,
    bins: [
      { value: 10 },
      { value: 14 },
      { value: 25 },
      { value: 10 },
      { value: 15 },
      { value: 25 },
      { value: 10 },
    ],
  },
  {
    // bin: 0,
    bins: [
      { value: 10 },
      { value: 10 },
      { value: NaN },
      { value: 10 },
      { value: 10 },
      { value: 10 },
      { value: 1 },
    ],
  },
  {
    // bin: 1,
    bins: [
      { value: 0 },
      { value: 14 },
      { value: 27 },
      { value: 40 },
      { value: 50 },
      { value: 60 },
      { value: 70 },
    ],
  },
  {
    // bin: 2,
    bins: [
      { value: 80 },
      { value: 90 },
      { value: 100 },
      { value: 0 },
      { value: 15 },
      { value: 25 },
      { value: 40 },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: 10 },
      { value: 20 },
      { value: 30 },
      { value: 40 },
      { value: 50 },
      { value: 50 },
      { value: 50 },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: 0 },
      { value: 5 },
      { value: 10 },
      { value: 15 },
      { value: 20 },
      { value: 25 },
      { value: 30 },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: 35 },
      { value: 40 },
      { value: 45 },
      { value: 50 },
      { value: 55 },
      { value: 60 },
      { value: 65 },
    ],
  },
  {
    // bin: 3,
    bins: [
      { value: 70 },
      { value: 75 },
      { value: 80 },
      { value: 85 },
      { value: 90 },
      { value: 95 },
      { value: 100 },
    ],
  },
];
export { testData2 };
